import React from "react";
import { Container } from "react-bootstrap";

const AboutMe = () => {
    return (
        <Container className="mx-auto text-white text-center my-4">
            <h1 className="fs-1 fw-bolder">Club Atletico San Fernado</h1>
            <div>
                <p>
                    Estadio: Club Atlético San Fernando Dirección: La Encantada, Leales{" "}
                </p>
                <p> Clásico rival: Club Sportivo Bella Vista</p>
                <p> Fundación: 15/08/1959 (64 años cumple en 2023)</p>
                <p>Apodo: El Huracán Verde Categoría</p>
                <p>Actual: Liga Tucumana - Ascenso LTF.</p>
            </div>
            <h2>Nuestra Historia</h2>
            <p>
                NACIÓ DEL IMPULSO DE LOS TRABAJADORES DEL INGENIO SAN FERNANDO DE LEALES A
                FINES DEL AÑO 1959 Y FUE EL ULTIMO CLUB EN ADHERIRSE A LA DESAPARECIDA
                ASOCIACIÓN CULTURAL JUSTAMENTE UNO DE SUS FUNDADORES DON ALBERTO HERRERA,
                SERIA PRESIDENTE EN EL AÑO 2005 CUAN SAN FERNANDO OBTUVO SU PRIMER
                CAMPEONATO DE LA LIGA TUCUMANA DE FÚTBOL. CON LA UNIFICACION DE LAS LIGAS
                EN EL AÑO 1977, PASO A MILITAR A LA LIGA TUCUMANA DE FUTBOL EN 1986 SE
                CORONO CAMPEON DE LA ZONA C DE PRIMERA B POR LO OUE ACCEDIO A PRIMERA A,
                PERO VOLVIÓ A DESCENDER. EN 1992 OTRA VEZ SE CORONO CAMPEÓN DE LA PRIMERA
                B. HACIA EL AÑO 2002 LA DIRIGENCIA DEL CLUB DE LEALES PRESIDIDA EN ESE
                ENTONCES POR JORGE CORDOBA, SE PLANTEO LA NECESIDAD DE UN CAMBIO, ESTO LO
                LLEVO A TRANSITAR UNA SENDA DE TRIUNFOS SIN PRESIDENTES EN SU HISTORIA, NO
                OBSTANTE NO FUE UN CAMINO LIBRE DE ESPINAS, EL TORNEO INICIACIÓN TUVO UN
                COMIENZO DESASTROSO, QUE LLEVO A SU TÉCNICO ANGEL RAMOS A LA RENUNCIA EN
                LA QUINTA FECHA, ASÚMIENDO EN SU REEMPLAZO LUIS BENITO SOSA QUE SE IRÍA AL
                FINALIZAR EL APERTURA. ASUMIO AMERICO BANEGAS EN EL CLAUSURA QUE LO
                LLEVARÍA POR SENDERO DE CONQUISTAS EXCEPCIONAL. EN EL AÑO 2004 VIVIÓ UNA
                DE LAS RAREZAS DEL FÚTBOL. POR UN LADO EL PLANTEL JUGABA POR JUGAR PUES NO
                HABÍA NI SUELDOS NI PREMIOS. POR OTRO LADO EN SU EQUIPO JUGABAN 4 HEMANOS
                (MARTIN EDUARDO, CARLOS ALBERTO Y VICTOR SEBASTIAN )Y UN PRIMO ( MAXIMO
                ROBERTO) TODOS APELLIDOS LEGUIZAMON. ALGO QUE YA HABÍA OCURRIDO EN LA
                ENTIDAD DEL ESTE POR LA DÉCADA DEL 70 CUANDO CUATRO HERMANOS (TODOS
                LEGUIZAMON) INTEGRABAN EL PLANTEL. ESTE DATO NO ES MENOR PUES EN LA FINAL
                DEL CAMPEONATO 2005 EN EL QUE SAN FERNANDO SE CORONO CAMPEON, SPORTIVO
                ALINEO A LOS TRES HERMANOS FERNANDEZ, MIENTRAS SAN FERNANDO A LOS 4
                LEGUIZAMON. ALGO NUNCA VISTO, QUE YO SEPA EN LA HISTORIA DEL FÚTBOL
                TUCUMANO. EN EL TORNEO DEL INTERIOR 2006 EN EL AÑO 2006 DISPUTO EL TORNEO
                DEL INTERIOR DONDE EN LA PRIMERA FECHA PERDIO CON SPORTIVO 2 a 1
                (22/01/06), CON YPF 3 A 2 (28/01/06) , LE GANO A ESTRELLA DEL NORTE 5 A 0
                (06/02/06) ; EN LOS DESQUITES LE GANO A SPORTIVO 4 A 2 (12/02/06) .SUPERO
                A YPF POR 2 A 1 16/02/06) Y LE GANO 5 A 1 A ESTRELLA DEL NORTE (25/02/06).
                PASO A LA SIGUIENTE FASE, EN DICHA INSTANCIA ELIMINO A SPORTIVO ALBERDI DE
                JUJUY, EN EL PARTIDO DE IDA FUE UN 3 A 0 (12/03/06) Y O A O EN EL PARTIDO
                DE VUELTA 19/03/06) CLASIFICANDO A UNA NUEVA ETAPA. ESTA VEZ EL RIVAL FUE
                CENTRAL ARGENTINO DE SANTIAGO DEL ESTERO QUE GANO EL PRIMER PARTIDO POR 1
                A 0 (26/03/06) PERO LOS DE LEALES SE RECOMPUSIERON Y GANARON 3 A O
                (02/04/06) EN UN PARTIDO QUE NO ESTUVO LEJOS DE LA POLÉMICA , DONDE HUBO
                PROTESTA DE LOS SANTIAGUENOS POR EL DESEMPENO DE LA TERNA ARBITRAL,
                AGRESIONES A LOS JUGADORES POR PARTE DE LOS HINCHAS LOCALES Y EL RETIRO DE
                LA VISITA A OS VESTUARIOS, UNA VEZ ALLÍ Y ANTE LA SITUACIÓN LA GENTE DE
                SANTIAGO DIRECTAMENTE NO SALIO A JUGAR, EL PARTIDO HABÍA ESTADO SUSPENDIDO
                EN LA PRIMERA ETAPA, Y YA EN LA SEGUNDA SE SUSPENDIO DEL TODO CUANDO SE
                JUGABAN 63 MINUTOS. EN LA SIGUIENTE ETAPA ELIMINO A UNIÓN SANTIAGO (DE
                SANTIAGO DEL ESTERO), CON UN O A O EN EL PARTIDO DE IDA ( 10/04/06) Y UN
                TRIUNFO EN EL PARTIDO DE VUELTA POR 2 A 0 (16/04/06) . EN LA ETAPA
                POSTERIOR ENFRENTO NUEVAMENTE A SPORTIVO GUZMAN , GANANDO EL CAPITALINO 2
                A 1 EL PARTIDO DE IDA (24/04/06) Y EN LA VUELTA (01/05/06) GANO EL EQUIPO
                DEL ESTE POR UNO A CERO CON GOL DE MARTIN MARTINEZ, LA DEFINICIÓN POR
                PENALES FUE PARA EL EQUIPO VERDE POR 8 A 7 EN EL QUE EL ARQUERO RAUL GEREZ
                ATAJO DOS PENALES, CONSIGUIENDO EL PASAJE A LA FINAL. YA EN LA FINAL
                ENFRENTO A 9 DE JULIO DE CORDOBA, PERDIÓ EN EL PARTIDO DE IDA 1 A 0
                (07/05/06) Y 1 A O EN EL PARTIDO DE VUELTA ( 14/05/06) QUEDANDOSE A UN
                PASO DEL ARGENTINO B . PESE A ESO TUVO LA CHANCE DE JUGAR LA PROMOCION, EN
                LA QUE ENFRENTO A JUVENTUD ALIANZA DE SAN JUAN GANANDO EL PRIMER PARTIDO
                (21/05/06) POR 1 A O CON GOL DE MARTIN MARTINEZ EN EL PARTIDO DE VUELTA
                LOS SAN JUANINOS GANARON POR 1 A 0 (27/05/06) Y SE QUEDARON CON LA PLAZA
                POR VENTAJA DEPORTIVA. UNA NUEVA VUELTA DE TURCA TENDRÍA ESTA HISTORIA
                PUES FUE INVITADO A JUGAR UN CUADRANGULAR POR UN PLAZA PARA LA REGIÓN ANTE
                LA DESERCIÓN DE ALGUNOS EQUIPOS CLASIFICADOS ALGO EN LO QUE TUVO QUE VER Y
                MUCHO LAS GESTIONES DE SU PRESIDENTE ALBERTO HERRERA. LE TOCO ENFRENTAR A
                SPORTIVO ESTUDIANTES DE SAN LUIS, SIENDO EL RESULTADO DEL PRIMER ENCUENTRO
                UN 0 A 0 (08/07/06) Y OTRO EMPATE, ESTA VEZ 1 A 1 (16/07/06) CON GOL DE
                MIGUEL FERNANDEZ, ESTE PARTIDO TUVO DE TODO, PIERNA FUERTE, PELEAS,
                EXPULSIONES (3 POR SAN FERNANDO Y DOS POR EL LOCAL) Y HASTA UNA DEFINICIÓN
                POR PENALES EN LA OUE EL LOCAL GANO POR 5 A 4 (iPERO SE ERRARON 4 PENALES
                POR EL LOCAL Y 5 POR LA VISITA!!!)
            </p>
        </Container>
    );
};

export default AboutMe;
